### ISSUE TITLE
소스코드

### ISSUE THREAD

**Issue by padosum** [Admin0/bucket#2]
안녕하세요 블로그에 버킷리스트를 적어보려고 찾아보다가 발견했는데 정말 재밌게 잘 만드셔서..
혹시 소스를 가져다 써도 되나요?? 메일 주소가 안나와 있어서 여기다 남깁니다!!

**Comment by Admin0** [comment]
네, 마음껏 쓰세요 ^^

**Comment by padosum** [comment]
감사합니다 잘 사용하겠습니다!
